# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=100)),
                ('createdDate', models.DateField(auto_now_add=True)),
                ('updatedDate', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'billing_contact',
                'ordering': ['-createdDate'],
            },
        ),
        migrations.AlterModelOptions(
            name='applications',
            options={'ordering': ['-createdDate']},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['-createdDate']},
        ),
        migrations.AlterModelOptions(
            name='projectusers',
            options={'ordering': ['-createdDate']},
        ),
        migrations.AlterModelOptions(
            name='userrequest',
            options={'ordering': ['-createdDate']},
        ),
        migrations.RenameField(
            model_name='applications',
            old_name='address',
            new_name='street_address',
        ),
        migrations.AddField(
            model_name='applications',
            name='city',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applications',
            name='country',
            field=models.CharField(default='Canada', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applications',
            name='createdDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applications',
            name='postal_code',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applications',
            name='region',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applications',
            name='updatedDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='createdDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrequest',
            name='updatedDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='applications',
            name='billing_contact',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.BillingContact'),
        ),
    ]
