# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-28 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171121_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectusers',
            name='status',
            field=models.IntegerField(choices=[(0, 'Invited'), (1, 'Pending'), (2, 'Active')], default=0),
        ),
    ]
