# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-28 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171128_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectusers',
            name='agreementCheck',
            field=models.BooleanField(default=False),
        ),
    ]
