# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-30 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181030_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_ICGC_access',
            field=models.BooleanField(default=False),
        ),
    ]
