# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-25 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_projects_project_icgc_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='invoice_consent',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
