# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-29 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_applications_invoice_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingcontact',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingcontact',
            name='phone',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
